### ISSUE TITLE
Choose the format test

### ISSUE THREAD

**Issue by cafmendo** [inglesBrain/IinglesBrain#10]
====================Test model 1===========
Complete the blank space.
1)
2)
3)
4)
5)
====================Test model 1===========
Choose the correct letter.
1)
a. b. c.
2)
a. b. c.
3)
a. b. c.
4)
a. b. c.
5)
a. b. c.

**Comment by jpcrespo** [comment]
====================Test model 1===========
Complete the blank space.
1)si
2)si
3)si
4)nop
5)si
====================Test model 1===========
Choose the correct letter.
1)a
a. b. c.
2)a
a. b. c.
3)
a. b. c.
4)b
a. b. c.
5)a
a. b. c.

**Comment by jpcrespo** [comment]
ahora cerralo tu
